# Configura o ambiente com Node 20
[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

# Instala (automático) e constrói o site
[phases.build]
cmds = ["npm run build"]

# Inicia o servidor estático na pasta dist
[start]
cmd = "npx serve -s dist -l 80"